### PR TITLE
added bootstrap for links

### PR DESCRIPTION
**Pull request by sainad2222**
added only for half if you like this I'll consider adding to remaining

### CODE REVIEW

**Comment by eswar2001** [comment]
Dark Theme missing. I found some bugs and missing tags.

**Comment by sainad2222** [comment]
I agree with dark theme. But when I run locally running as a HTML file everything was fine

**Comment by eswar2001** [comment]
How to run locally?
1.Install nodejs

2.clone the repo and open in your choice of editor

3.open cmd or terminal or powershell in the cloned dir and run 'npm install'

4.run 'npm start' to run

**Comment by eswar2001** [comment]
try running like this

**Pull request closed without merging**
